[tool.black]
    line-length = 120
    target-version = ['py310']
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | venv

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/
    '''