USER_ALREADY_EXISTS = "User already exists"
USER_NOT_FOUND = "User not found"
USER_DOES_NOT_EXIST = "User does not exist"
PASSWORD_INCORRECT = "Password incorrect"
INTERNAL_SERVER_ERROR = "Internal Server Error"
